export type Concept = {
  name: string;
  memory: string;
  signal: string;
  use: string;
  steps?: string[];
  example: string;
  caution: string;
};

export type Topic = {
  id: string;
  number: string;
  title: string;
  subtitle: string;
  question: string;
  answer: string;
  bridge: string;
  color: string;
  concepts: Concept[];
  rapid: string[];
  examLine: string;
};

export const topics: Topic[] = [
  {
    id: "definition", number: "01", title: "Definition", subtitle: "What strategy actually is", color: "lime",
    question: "What does the organization want to achieve—and how will it create value?",
    answer: "Strategy is a coherent way to create and capture value through choices. It is broader than a goal, a tactic, or simply doing today’s activities more efficiently.",
    bridge: "A direction is not enough. Next ask: what is happening outside the firm, and where should it compete?",
    examLine: "Use Definition models when the scenario is confused about meaning, value creation, strategic level, or whether observed behavior is intended.",
    concepts: [
      { name: "Value Stick", memory: "WTP ↓ Price ↓ Cost ↓ WTS", signal: "The case mentions customer value, price, margin, employees, suppliers, or shared value.", use: "Map who receives value. Customer delight = WTP − price; firm margin = price − cost; supplier/employee surplus = cost − WTS; total value = WTP − WTS. Raise WTP or lower WTS while deciding how much value the firm captures.", steps: ["Identify customer WTP", "Locate price and cost", "Identify employee/supplier WTS", "Choose a value lever", "Check stakeholder trade-offs"], example: "Patagonia can raise WTP through credible sustainability and lower employee WTS because purpose makes the job more attractive.", caution: "Profit is only the firm’s captured slice. Higher price may capture value without creating more total value." },
      { name: "Mintzberg’s 5 Ps", memory: "Plan, Ploy, Pattern, Position, Perspective", signal: "The scenario asks what strategy means, shows a repeated behavior, a market stance, culture, or a competitive maneuver.", use: "Classify the evidence: intended course (Plan), maneuver (Ploy), consistent realized behavior (Pattern), market relationship (Position), or shared worldview (Perspective). Several Ps can coexist and cause one another.", example: "Ryanair’s low-cost worldview is Perspective; its single-aircraft plan supports a low-cost Position; repeated no-frills choices become a Pattern; aggressive entry pricing can be a Ploy.", caution: "Do not force a scenario into only one P. State which P is most visible and how it relates to the others." },
      { name: "Schools of Strategy", memory: "3 prescribe; 7 describe", signal: "The case contrasts formal analysis with vision, learning, politics, culture, environmental reaction, or transformation.", use: "Prescriptive: Design = fit, Planning = formal program, Positioning = analytical market choice. Descriptive: Entrepreneurial = vision, Cognitive = mental process, Learning = emergence, Power = negotiation, Cultural = shared beliefs, Environmental = reaction, Configuration = transformation.", example: "A founder-led pivot reflects the Entrepreneurial school; experiments that gradually reveal a new model reflect Learning; a regulator-forced response reflects Environmental.", caution: "Each school illuminates part of formation. Taken to an extreme, planning becomes ritual and learning becomes drift." },
      { name: "Strategic Management Cycle", memory: "F–I–E, then loop", signal: "The issue is where a decision belongs: choosing direction, executing it, or reviewing results.", use: "Formulation chooses what and why; implementation allocates resources and turns choices into work; evaluation measures results and environmental change, feeding adjustments back to both.", example: "Choosing a subscription model is formulation; creating the product team is implementation; reviewing churn and adapting the offer is evaluation.", caution: "The phases are connected, not a rigid one-way waterfall. Formation often continues during implementation." },
      { name: "Strategy vs Tactics vs OE", memory: "Direction → move → efficiency", signal: "The case confuses a promotion, process improvement, or target with strategy.", use: "Strategy is long-term coherent choice; tactics are short, concrete moves; operational effectiveness (OE) means doing similar activities better. Sustainable positioning means different activities or doing them differently.", example: "A temporary discount is a tactic. Faster warehouse picking is OE. A low-cost model built around a different activity system is strategy.", caution: "OE is essential but imitable; competitive convergence means everyone improves without durable relative advantage." },
    ],
    rapid: ["Strategy = value creation + choices + coherence", "Profit ≠ total value", "Observed pattern may differ from intended plan", "Formulate → implement → evaluate → learn", "OE improves the race; positioning changes the race"],
  },
  {
    id: "competition", number: "02", title: "Competition", subtitle: "Outside-in analysis and positioning", color: "orange",
    question: "What external forces shape the game, how attractive is the industry, and where can the firm position itself?",
    answer: "Use an external audit to turn environmental facts into opportunities and threats, then select a competitive or growth position with explicit trade-offs.",
    bridge: "External attractiveness cannot explain why firms in the same industry perform differently. Next look inside the firm’s resources.",
    examLine: "Use Competition models when the clue is outside the company: regulation, technology, customer power, rivalry, new markets, substitutes, or growth direction.",
    concepts: [
      { name: "External Audit + PESTEL", memory: "Politics, Economy, Society, Tech, Environment, Law", signal: "The scenario features macro change outside one firm’s control.", use: "Identify specific, quantified, actionable external trends or facts; classify with PESTEL; label each as opportunity, threat, or both; derive a response only after the factor is stated.", example: "EU AI regulation is a Legal/Political threat through compliance cost and an opportunity for a trusted-AI position.", caution: "Do not put a strategy (‘expand into Asia’) inside PESTEL. The factor must be external (‘Asian demand grows 12%’)." },
      { name: "Porter’s Five Forces", memory: "Entrants, Suppliers, Buyers, Substitutes, Rivalry", signal: "The question is industry profitability or pressure from ecosystem actors.", use: "Rate each force strong/weak and give the mechanism. Strong collective forces reduce profit potential. Connect PESTEL events to the force they change.", steps: ["Define the industry boundary", "Assess five forces with evidence", "Find the strongest force", "Judge profit potential", "Recommend how to defend or reposition"], example: "Generative AI has strong supplier power where scarce chips/cloud capacity are concentrated, while open-source substitutes put a ceiling on price.", caution: "It analyzes industry structure, not the resources of one firm. Never treat complementors as a sixth force without explanation." },
      { name: "Megatrends", memory: "Long + global + transforming + cross-industry", signal: "The change unfolds over 10–20+ years and affects many sectors.", use: "Justify why it is a megatrend using duration, global reach, transformation, cross-industry relevance, and strategic implications.", example: "Aging populations reshape health, work, finance, housing, and mobility across countries—Silver Society, not a short fad.", caution: "A fashionable technology or one-year sales bump is not automatically a megatrend." },
      { name: "Porter’s Generic Strategies", memory: "Broad/narrow × cost/unique", signal: "The case asks how to compete or shows price advantage, uniqueness, or a niche.", use: "Choose cost leadership, differentiation, cost focus, or differentiation focus. Show the activity system and required trade-offs.", example: "A specialized cybersecurity firm serving only hospitals with compliance expertise follows differentiation focus.", caution: "‘Stuck in the middle’ means neither defensible low cost nor valued uniqueness—not simply using a hybrid once." },
      { name: "Ansoff Growth Matrix", memory: "Old/new product × old/new market", signal: "The problem is choosing a growth route.", use: "Existing product/existing market = penetration; existing/new = market development; new/existing = product development; new/new = diversification. Risk generally rises across that sequence.", example: "Starbucks entering India with coffee = market development; Amazon entering cloud services = diversification.", caution: "Be precise about what counts as new to the firm, and do not confuse a new channel with a new market automatically." },
      { name: "Blue Ocean + ERRC", memory: "Eliminate, Reduce, Raise, Create", signal: "The market is crowded and the firm seeks uncontested demand or noncustomers.", use: "Break the value–cost trade-off through value innovation. Use ERRC, six paths, and three tiers of noncustomers to redraw the value curve.", example: "Nintendo Wii reduced raw processing power, raised ease of use, and created motion gaming for families and seniors.", caution: "Blue oceans do not stay blue forever. The firm still needs resources and execution to defend the new space." },
      { name: "Trade-offs + Door Test", memory: "Choose; then ask reversible?", signal: "The company tries to serve incompatible positions or faces a high-stakes decision.", use: "Trade-offs protect a position by limiting what not to do. For decisions: one-way doors are consequential/irreversible and deserve slow analysis; two-way doors are reversible and should be decentralized and fast.", example: "Testing a new landing page is two-way; buying a rival for €10bn is largely one-way.", caution: "Speed is not always agility. Classify reversibility and downside before choosing the decision process." },
    ],
    rapid: ["PESTEL = macro environment", "Five Forces = industry profit pressure", "Generic Strategy = competitive position", "Ansoff = growth direction", "Blue Ocean = new demand + value innovation", "Strategy requires saying no"],
  },
  {
    id: "resources", number: "03", title: "Resources", subtitle: "Inside-out advantage", color: "blue",
    question: "What does this firm possess or do that lets it outperform—and can that advantage last?",
    answer: "Audit tangible, intangible, human, organizational, and digital resources; test them with VRIO; then build the ability to renew them as conditions change.",
    bridge: "Knowing strengths and opportunities does not yet produce a strategy. Next ask how strategy is actually formed under uncertainty.",
    examLine: "Use Resources models when firms in the same market perform differently, when a capability is hard to copy, or when strengths and weaknesses must meet opportunities and threats.",
    concepts: [
      { name: "Internal Audit + RBV", memory: "Look inside before looking alike", signal: "The case highlights patents, brand, talent, culture, processes, data, partnerships, or IT.", use: "Inventory tangible, intangible, human, organizational, knowledge, flexibility, and technology resources. RBV explains performance through heterogeneous and imperfectly mobile resources.", example: "Two airlines face the same fuel prices, but one has a culture and operating system that supports fast turnarounds.", caution: "A resource is not an advantage merely because the firm owns it. Test what it enables." },
      { name: "VRIO", memory: "Valuable? Rare? Imitable? Organized?", signal: "The question asks whether a particular resource creates sustainable competitive advantage.", use: "V only → parity; V+R → temporary advantage; V+R+costly I → potential sustained advantage; O determines whether the firm captures it. Explain imitability through path dependence, causal ambiguity, social complexity, or time compression.", steps: ["Name one precise resource", "Test V", "Test R", "Explain cost of imitation/substitution", "Check structures and incentives", "State the competitive outcome"], example: "Salesforce’s AppExchange is valuable, rare at its depth, costly to imitate due to network effects and path dependence, and supported by partner systems: sustained advantage.", caution: "Analyze resources one by one. ‘Strong brand’ without evidence is too vague; Organization is not a fourth resource quality but the exploitation mechanism." },
      { name: "Ex-ante / Ex-post Limits", memory: "Buy before / protect after", signal: "The case asks why a firm acquired a resource cheaply or why rivals cannot erode its rents later.", use: "Ex-ante limits reduce competition before the position is won (information asymmetry, uncertainty, first mover). Ex-post isolating mechanisms protect it afterward (patents, switching costs, causal ambiguity, social complexity).", example: "Salesforce entered cloud CRM while incumbents doubted it (ex-ante); ecosystem network effects and switching costs now protect it (ex-post).", caution: "First-mover status alone is not protection; identify the mechanism that persists." },
      { name: "Dynamic Capabilities", memory: "Sense → Seize → Reconfigure", signal: "The environment changes quickly and yesterday’s resource may become tomorrow’s rigidity.", use: "Sense opportunities/threats; seize them through timely commitment; reconfigure assets, processes, structure, and talent to maintain evolutionary fitness.", example: "Apple sensed mobile computing, seized it with iPhone, then reconfigured supply chains and built the app/service ecosystem.", caution: "Ordinary capabilities operate the business; dynamic capabilities change the resource base. Constant change without direction is not a capability." },
      { name: "IT’s Four Roles in DC", memory: "Context, Enabler, Embedded, Outcome", signal: "The question asks how information systems relate to agility or capability renewal.", use: "IT can create the digital context, enable sensing/seizing, be embedded in a capability, or emerge as an outcome of capability building.", example: "Analytics enables sensing; a data-driven supply chain embeds IT; innovation capability can produce a new platform as outcome.", caution: "Do not reduce IT to infrastructure. Its role may deepen and multiple roles can coexist." },
      { name: "SWOT / TOWS", memory: "SO win, WO build, ST shield, WT survive", signal: "The task asks to synthesize internal and external audits into strategic actions.", use: "S/W are internal; O/T external. Match SO, convert WO, neutralize ST, defend WT. Quantify, prioritize, and write an action—not just four lists.", example: "Strong AI talent (S) + rising enterprise demand (O) → launch a secure vertical model (SO). Weak compliance (W) + new regulation (T) → partner or build governance before expansion (WT).", caution: "SWOT is a snapshot, subjective, and easily becomes vague. Pair it with evidence, prioritization, and dynamic capabilities." },
    ],
    rapid: ["RBV explains firm differences", "VRIO predicts parity/temporary/sustained advantage", "Ex-ante wins the resource; ex-post protects it", "Dynamic capabilities renew resources", "SWOT must end in SO/WO/ST/WT action"],
  },
  {
    id: "formation", number: "04", title: "Formation", subtitle: "Crafting strategy under uncertainty", color: "violet",
    question: "How does a real strategy emerge from analysis, action, learning, and leadership?",
    answer: "Diagnose the pivotal challenge, choose a guiding policy, coordinate actions, and continuously navigate between deliberate intent and emergent learning.",
    bridge: "A coherent strategy still fails if structure, people, and systems pull in another direction. Next align the organization.",
    examLine: "Use Formation when the scenario involves a pivot, failed plan, experimentation, learning, uncertainty, strategic drift, or a list of goals without a real approach.",
    concepts: [
      { name: "Rumelt’s Strategy Kernel", memory: "Diagnose → Guide → Act", signal: "The case asks whether a strategy is good or presents a messy challenge needing focus.", use: "Diagnosis simplifies reality to the critical challenge; guiding policy states the overall approach; coherent actions reinforce one another and implement the policy.", steps: ["Name the pivotal challenge", "Explain its mechanism", "Choose one overall approach", "List mutually reinforcing actions", "Show what will not be done"], example: "Diagnosis: churn comes from poor onboarding, not price. Policy: win the first 7 days. Actions: redesign setup, staff success calls, measure activation, pause broad discounting.", caution: "A target (‘grow 20%’) is not a strategy. Avoid fluff, bad objectives, long wish lists, and refusing to choose." },
      { name: "Deliberate–Emergent Spectrum", memory: "Intended ≠ realized", signal: "A plan was abandoned, an unexpected pattern succeeded, or the environment is unstable.", use: "Deliberate = intended and realized; unrealized = intended but not achieved; emergent = realized without original intent; realized strategy is the observed pattern combining both.", example: "Netflix intended to lead home entertainment; streaming and original content emerged through technology, data, and learning; Qwikster was unrealized/reversed.", caution: "Pure planning needs perfect control; pure emergence lacks direction. Most effective strategies blend both." },
      { name: "Strategy as Craft", memory: "Potter, not blueprint", signal: "Learning-by-doing, tacit knowledge, and hands-on adjustment are central.", use: "Integrate past patterns, present reality, and future intent. Formulation and implementation interact; operational action reveals strategic knowledge.", example: "A product team shapes an offering through customer use data while holding a stable mission, like a potter responding to clay.", caution: "Craft is not improvisation without discipline. It still requires a coherent intent and pattern recognition." },
      { name: "Strategy Life Cycle", memory: "Converge, then leap", signal: "Long incremental refinement is interrupted by a major reorientation.", use: "During convergence, improve and elaborate the current model. During divergence, respond to discontinuity with a quantum strategic leap. Diagnose signal vs noise.", example: "Netflix refined DVD subscription for years, then reoriented to streaming when technology and behavior crossed a threshold.", caution: "Too much change destroys capability; too much continuity becomes inertia." },
      { name: "Five Craft Capabilities", memory: "Know, stabilize, pattern, detect, reconcile", signal: "The prompt asks what leaders need to form strategy well.", use: "Know the business intimately; manage stability; manage patterns; detect discontinuities; reconcile change and continuity.", example: "Recognizing binge-watching as signal rather than noise let Netflix turn a behavioral pattern into release strategy.", caution: "Dashboards cannot replace intimate operational understanding and judgment." },
      { name: "Fast Strategic Decisions", memory: "Intuition, conflict, no politics", signal: "A leadership team must make frequent, high-quality decisions quickly.", use: "Build collective intuition through real-time information; stimulate quick, evidence-based conflict; defuse political behavior with shared goals and transparent criteria.", example: "Teams debate multiple content investments vigorously, then an informed captain decides with shared audience data.", caution: "Quick conflict is constructive task debate—not prolonged personal or departmental conflict." },
    ],
    rapid: ["Good strategy = diagnosis + guiding policy + coherent actions", "Goals and buzzwords are not strategy", "Realized = deliberate + emergent", "Stable context leans planned; turbulence leans emergent", "Craft combines analysis, judgment, and learning"],
  },
  {
    id: "organization", number: "05", title: "Organization", subtitle: "Structure follows strategy", color: "teal",
    question: "What must change inside the organization so the chosen strategy can actually happen?",
    answer: "Align strategy, structure, systems, culture, skills, people, and leadership style; choose a structure that fits size, environment, complexity, and strategic direction.",
    bridge: "Alignment makes action possible, but ‘possible’ is not automatically responsible. Next test the strategy’s ethical and stakeholder consequences.",
    examLine: "Use Organization when the symptom is silos, slow decisions, duplicated resources, unclear authority, growth beyond the current structure, or tension between operations and innovation.",
    concepts: [
      { name: "Organizational Alignment", memory: "Fit creates force", signal: "A reasonable strategy underperforms because components contradict each other.", use: "Check internal structural fit, size–structure fit, size–planning fit, and environment–structure fit. Alignment itself can become a hard-to-copy advantage.", example: "A dynamic market with every decision centralized at headquarters shows environment–structure misfit.", caution: "Perfect fit never lasts. Alignment must be maintained as strategy and environment evolve." },
      { name: "McKinsey 7S", memory: "3 hard + 4 soft", signal: "A transformation or merger needs a whole-system alignment diagnosis.", use: "Hard: Strategy, Structure, Systems. Soft: Shared values, Skills, Staff, Style. Find contradictions and change mutually reinforcing elements, not one box alone.", example: "An innovation strategy fails when incentives reward only cost reduction: Strategy–Systems–Style misalignment.", caution: "The model diagnoses alignment; it does not select the competitive strategy for you." },
      { name: "Structure Follows Strategy", memory: "New choice → new coordination", signal: "The firm changes product, geography, integration, or strategic priority.", use: "Structure shapes how objectives/policies are set and how resources flow. A strategy shift may require new decision rights, reporting, coordination, and funding.", example: "Global expansion may require geographic divisions with local authority rather than one domestic functional hierarchy.", caution: "Restructuring without a strategic reason creates cost and confusion; strategy and structure also influence each other." },
      { name: "Integration Strategies", memory: "Back, forward, sideways, related", signal: "The firm acquires suppliers, distributors, competitors, or related businesses.", use: "Backward vertical = suppliers; forward vertical = distribution; horizontal = competitors; related diversification = adjacent businesses. Design differentiation, integration mechanisms, conflict resolution, and shared information.", example: "Apple stores are forward integration and require strong coordination between retail, product, and service operations.", caution: "Acquisition logic and organizational integration are different questions; synergy does not happen automatically." },
      { name: "Structural Options", memory: "Simple → Functional → Divisional → Matrix/SBU", signal: "The case asks which structure fits size, product range, geography, or coordination needs.", use: "Simple: speed/small scale. Functional: specialization/one line. Divisional: market focus/multiple lines. Matrix: dual integration/complex projects. SBU: semi-autonomous businesses plus corporate portfolio logic.", example: "A diversified global firm may use SBUs; a specialist manufacturer in a stable market may use functions.", caution: "Every structure trades speed, coordination, cost, accountability, and flexibility. Name both fit and downside." },
      { name: "Structural Ambidexterity", memory: "Exploit + explore", signal: "Reliable operations conflict with digital innovation or experimentation.", use: "Separate but coordinate exploitation and exploration. CIO often leads stable, secure, efficient IT; CDO leads digital innovation, customer experience, and new models. Share platforms/governance and allocate resources dynamically.", example: "A CDO pilots AI services while the CIO secures shared data and production infrastructure.", caution: "Separate units can drift apart. Complementary roles need explicit boundaries, shared values, and integration mechanisms." },
      { name: "Convergence vs Upheaval", memory: "Change in system / change of system", signal: "The organization faces either normal improvement or a discontinuity demanding transformation.", use: "Convergence = incremental refinement and fit. Upheaval/frame-breaking = rapid system-wide change to mission, power, structure, people, and processes.", example: "Optimizing a mature product is convergence; an existential substitute may demand frame-breaking reorganization.", caution: "Use upheaval only when incremental adaptation is insufficient; it is costly and risky." },
    ],
    rapid: ["Misfit can destroy a sound strategy", "7S: Strategy Structure Systems / Shared values Skills Staff Style", "No best structure—only best fit", "CIO exploits; CDO explores", "Convergence improves the system; upheaval changes the system"],
  },
  {
    id: "ethics", number: "06", title: "Ethics", subtitle: "Responsibility as strategy", color: "pink",
    question: "Is the strategy right, fair, sustainable, and robust to stakeholder scrutiny—not merely effective?",
    answer: "Treat ethics as strategic value creation and risk management. Integrate stakeholder expectations into analysis, design, metrics, culture, and everyday decisions.",
    bridge: "Responsible intent needs evidence. Next define what to measure, how to control execution, and how to avoid measurement dysfunction.",
    examLine: "Use Ethics when actions affect vulnerable stakeholders, privacy, AI bias, sustainability, reputation, legitimacy, or conflicts between profit and responsibility.",
    concepts: [
      { name: "Ethics + Amplification", memory: "Scale, Time, Complexity, Visibility", signal: "A corporate decision has broad or long-lived moral consequences.", use: "Evaluate right/wrong conduct and stakeholder expectations. Organizations amplify consequences across people, years, jurisdictions, and public scrutiny.", example: "A biased automated lending model can affect millions, persist in data, cross legal systems, and trigger public backlash.", caution: "Legal compliance is only the floor; an effective but unethical strategy can create ethical debt and destroy value." },
      { name: "Carroll’s CSR Pyramid", memory: "Profit, Law, Ethics, Philanthropy", signal: "The prompt asks which responsibility is required, expected, or desired.", use: "Economic: be viable. Legal: obey rules. Ethical: do what is fair beyond law. Philanthropic: voluntary citizenship. Extend digitally to privacy, security, unbiased AI, inclusion, and digital well-being.", example: "GDPR compliance is legal; proactively explaining algorithms is ethical; funding digital access is philanthropic.", caution: "The layers can conflict and operate simultaneously; do not treat philanthropy as compensation for unethical core operations." },
      { name: "Corporate Digital Responsibility", memory: "E–S–G of digital", signal: "The dilemma involves AI, data, surveillance, automation, access, e-waste, or system reliability.", use: "Check environmental footprint/e-waste; social fairness, inclusion, well-being, freedom, automation; governance of data transparency, ownership, security, use, and autonomous systems.", example: "An AI hiring tool needs bias testing, data governance, explainability, privacy, and a human appeal process.", caution: "A model accuracy KPI alone misses distributional harm and rights." },
      { name: "CSR–Performance Curve", memory: "Too little and too much can cost", signal: "The case asks whether CSR pays or how much to invest.", use: "Use the U-shaped/nuanced relationship: underinvestment misses loyalty, risk mitigation, and differentiation; overinvestment can divert resources. Seek initiatives aligned with core capabilities, material stakeholders, and measurable impact.", example: "Energy efficiency supports both emissions reduction and cost advantage; unrelated symbolic donations may yield little strategic value.", caution: "Do not claim CSR always pays. Explain context, authenticity, materiality, and time horizon." },
      { name: "Ethics in Strategic Analysis", memory: "External + internal + value stick", signal: "You must integrate CSR rather than discuss it separately.", use: "External audit: regulation, activism, expectations. Internal audit: reputation, culture, compliance, innovation. Value stick: CSR can raise WTP, reduce costs, lower employee/supplier WTS, and reduce risk.", example: "Fair sourcing can stabilize suppliers (lower WTS), attract talent, and raise customer WTP if credible.", caution: "Greenwashing destroys trust; claims must match operating reality." },
      { name: "Ethical Implementation", memory: "Audit, stakeholders, risk, metrics, culture", signal: "The organization has values statements but harmful day-to-day choices.", use: "Integrate ethical audits, stakeholder impact, risk management, balanced KPIs, cultural alignment, education, codes, leadership example, and future scanning.", example: "Add safety and fairness gates to product reviews, assign owners, measure incidents, and link escalation to governance.", caution: "A code without incentives, voice, oversight, and visible leadership support becomes symbolic compliance." },
      { name: "Decision Heuristics", memory: "News, mirror, family + intent/harm/mitigation", signal: "A team needs a quick ethical check during a decision or sprint.", use: "Newspaper test: comfortable if public? Universality: acceptable if done to us? Mom/family test: proud to explain? Then scan intended benefits, unintended harm, vulnerable users, and mitigation.", example: "Before launching addictive notifications, ask who is vulnerable and add frequency controls and well-being metrics.", caution: "Heuristics flag risk; they do not replace a full stakeholder or legal analysis for high-stakes decisions." },
    ],
    rapid: ["Legal ≠ automatically ethical", "Corporate harm is amplified", "CSR can change WTP, cost, and WTS", "Optimal CSR is strategic and material", "Ethics lives in product and incentive micro-decisions"],
  },
  {
    id: "cpm", number: "07", title: "CPM", subtitle: "Measure, control, and learn", color: "yellow",
    question: "How do we know whether strategy is working, who is accountable, and what should change?",
    answer: "Connect strategy to financial and non-financial measures, budgets, responsibility, variance diagnosis, feedback, and learning—while guarding against gaming and tunnel vision.",
    bridge: "CPM supplies the control system, but teams still need focused, visible near-term outcomes. Next translate strategy through OKRs.",
    examLine: "Use CPM when the case gives financial statements, investments, accountability, KPIs, budgets, variances, incentives, or asks how to judge performance.",
    concepts: [
      { name: "CPM vs Management Control", memory: "System / bridge", signal: "The issue is executing strategy across the organization.", use: "CPM is the broad enterprise system of goals, measures, reviews, people, and learning. Management control is the bridge: strategy formulation → influence and resource use → task control.", example: "A Balanced Scorecard and review cadence are CPM; a manager using targets, feedback, and corrective action is management control.", caution: "Control should support learning, not only top-down compliance." },
      { name: "Theory + Dysfunctions", memory: "Agency, Motivation, Power / T-G-S-R", signal: "Metrics change behavior, bonuses misfire, or teams game targets.", use: "Agency aligns principal/agent via monitoring and incentives. Motivation needs expectancy, instrumentality, valence plus autonomy/mastery/purpose. Power asks who defines and controls measures. Prevent Tunnel vision, Gaming, Short-termism, suboptimization, and Rigidity.", example: "A call center rewarded only for call length may rush customers (gaming/suboptimization); balance with resolution and satisfaction.", caution: "What is measurable is not necessarily what matters. Every KPI creates behavioral pressure." },
      { name: "Three Financial Statements", memory: "P&L period, BS point, CF cash", signal: "The case provides revenue, profit, assets/debt, or cash movements.", use: "P&L: revenue − expenses → net income over a period. Balance sheet: Assets = Liabilities + Equity at a date. Cash flow: operating, investing, financing movements; reconciles profit with actual cash and balance changes.", example: "Buying equipment is investing cash outflow and increases assets; depreciation later lowers P&L profit without a current cash outflow.", caution: "Profit is not cash. Match period measures with period measures and point-in-time balances appropriately." },
      { name: "Ratio Families", memory: "Profit, liquidity, efficiency, leverage", signal: "The examiner asks to interpret performance or compare firms/time periods.", use: "Margins/ROA/ROE/ROCE show return; current/quick/OCF ratios show near-term solvency; turnover and DSO/DIO/DPO/CCC show asset use; debt-equity/equity ratio/interest coverage/DSCR show risk.", example: "CCC = DIO + DSO − DPO. Falling CCC means less time cash is tied up, if not achieved by damaging supplier relations.", caution: "A ratio needs a trend, benchmark, and business context. ROE can rise simply because leverage rises." },
      { name: "TVM + NPV", memory: "Discount future cash; accept NPV > 0", signal: "The scenario evaluates an acquisition, project, moonshot, or future cash flows.", use: "FV = PV(1+i)^n; PV = FV/(1+i)^n; NPV = Σ CFt/(1+r)^t. Choose a risk-appropriate discount rate; state assumptions and test sensitivity.", steps: ["Forecast incremental cash flows", "Choose horizon", "Choose/justify discount rate", "Discount each flow", "Subtract initial investment", "Test scenarios and strategic options"], example: "At 10% WACC, the lecture’s €10,000 project with €3k/€4k/€5k returns has NPV −€210.37: reject on financial grounds.", caution: "NPV is assumption-sensitive and may miss options, learning, and indirect strategic value. Never mix quarterly and annual figures without conversion." },
      { name: "Costs + ABC", memory: "Direct/indirect; fixed/variable; activity driver", signal: "A unit looks profitable until shared resources or behavior are traced correctly.", use: "Classify assignability and behavior. Standard costing finds price/usage variances. ABC assigns resource costs to activities, then cost objects through drivers.", example: "€300k support cost / 15k tickets = €20 per ticket; enterprise clients using 500 tickets consume €10k support each.", caution: "Allocation choices affect perceived profitability and political behavior; choose causal drivers." },
      { name: "Planning, Budgets, Responsibility", memory: "Plan → budget → measure → analyze → act", signal: "Accountability is unclear or the environment makes annual budgets stale.", use: "Strategic plan sets 3–5 year direction; annual/rolling/zero-based/activity budgets translate it. Cost, revenue, profit, and investment centers receive measures matching what managers control.", example: "An investment center can own ROI/ROCE because it controls profit and assets; a service department may be a cost center.", caution: "Apply controllability: do not reward or punish managers for variables they cannot influence." },
      { name: "Variance Analysis", memory: "Price, volume, mix, cost", signal: "Actual profit differs from budget and management needs the cause.", use: "Identify causal factors, disaggregate the total variance, vary one factor at a time, quantify profit effects, and stop when added complexity no longer improves decisions.", example: "Revenue missed because units fell, even though price rose; separate volume and price before acting.", caution: "Meeting budget is not synonymous with optimal performance. Interpret market changes and strategic shifts." },
      { name: "Performance Frameworks", memory: "Finance → balance → stakeholders → real-time", signal: "The task asks which measurement framework best fits the problem.", use: "DuPont decomposes financial returns; Tableau de Bord is a dashboard; BSC balances Financial, Customer, Internal Process, Learning & Growth; Performance Pyramid links hierarchy; Performance Prism begins with stakeholders; systems evolve toward adaptive real-time control.", example: "Meta’s long-term AI bet needs BSC evidence: financial spend/returns, users, ad-ranking processes, and R&D talent—not current profit alone.", caution: "A dashboard displays; a strategy map explains causal logic. Select measures from strategy, not from availability." },
    ],
    rapid: ["CPM is broad; management control is the execution bridge", "Profit ≠ cash", "NPV > 0 adds financial value", "Match center metrics to controllability", "Variance finds cause, not blame", "Balance lagging financials with leading non-financials"],
  },
  {
    id: "okrs", number: "08", title: "OKRs", subtitle: "Focused execution with learning", color: "red",
    question: "What must teams accomplish now, how will success be evidenced, and how will learning stay visible?",
    answer: "Set a small number of meaningful Objectives and 3–5 measurable outcome Key Results, align them transparently, review frequently, and pair them with conversations, feedback, and recognition.",
    bridge: "Scores and reflection feed evaluation, revealing environmental changes, resource gaps, and new patterns—so the strategy loop begins again.",
    examLine: "Use OKRs when strategy is too abstract, teams are misaligned, priorities are excessive, or progress needs transparent outcome measures without killing autonomy.",
    concepts: [
      { name: "Objective + Key Results", memory: "What + evidence of how far", signal: "The case has vague goals or activity lists without measurable outcomes.", use: "Objective: qualitative, valuable, action-oriented, ambitious but realistic. KRs: 3–5 specific, time-bound, challenging, verifiable outcomes whose completion means the objective was achieved.", example: "O: Make onboarding effortless. KR: Raise seven-day activation from 52% to 72% by Q3. ‘Run five workshops’ is an initiative, not an outcome KR.", caution: "Do not turn tasks into KRs. A KR should measure changed reality, with quality guardrails where needed." },
      { name: "OKR Implementation", memory: "Pick, measure, cycle, share, walk", signal: "The organization wants to introduce OKRs.", use: "Choose 3–5 priorities; define 3–5 KRs each; run annual and quarterly cycles; make all tiers public; designate a shepherd; check in weekly/monthly; score, reflect, revise, repeat. Roughly half of objectives can emerge bottom-up.", example: "Company retention objective connects to product activation, support resolution, and customer-success adoption OKRs with explicit dependencies.", caution: "Mechanical cascading wastes time. Alignment should be top-down, bottom-up, and horizontal." },
      { name: "OKR Superpowers", memory: "FATS: Focus, Align, Track, Stretch", signal: "The examiner asks why OKRs help execution.", use: "Focus commits scarce attention; Align & connect exposes dependencies; Track creates accountability and learning; Stretch combines committed and aspirational goals.", example: "A public cross-team KR makes the data dependency visible before launch rather than after failure.", caution: "Stretch is not permission for impossible targets or reckless behavior." },
      { name: "Scoring + Cadence", memory: "Green 71+, yellow 30–70, red <30", signal: "Progress is uncertain or goals need revision.", use: "Use completion scores, subjective self-assessment, and narrative reflection. Green: continue; yellow: continue/revise; red: revise/stop. Relevance beats blindly preserving the original target.", example: "A 45% KR may still reveal a breakthrough impediment; discuss evidence before labeling the team poor.", caution: "Score for learning, not compensation. Tying stretch OKRs tightly to bonuses encourages sandbagging and gaming." },
      { name: "CFRs", memory: "Conversations, Feedback, Recognition", signal: "Quarterly scores exist but development, trust, and learning are missing.", use: "Frequent conversations address progress and coaching; bidirectional feedback guides improvement; recognition celebrates actions and outcomes connected to shared goals.", example: "A monthly check-in asks ‘what do you need from me to succeed?’ and recognizes a team that surfaced a risk early.", caution: "Software cannot substitute for psychologically safe conversations." },
      { name: "Goal-Setting Risks", memory: "Narrow, risky, unethical, short, siloed", signal: "Aggressive targets produce corners cut, cooperation loss, or short-term behavior.", use: "Check specificity, difficulty, who sets goals, horizon, risk appetite, ethics, fairness, culture, intrinsic motivation, and whether learning goals fit better than performance goals.", example: "A sales target needs margin, customer-fit, and conduct guardrails; otherwise reps may discount or mis-sell.", caution: "In complex change, learning KRs may be better than premature performance KRs." },
      { name: "OKRs in the Strategy Loop", memory: "Direction with room to emerge", signal: "The question asks how OKRs connect to strategy formation, transitions, or CPM.", use: "Top-line intent supplies deliberate direction; bottom-up goals and reviews surface emergent information. During convergence OKRs refine execution; during upheaval they align a new direction. They are one CPM mechanism, not the strategy itself.", example: "A transformation objective fixes the destination while team-defined KRs allow experiments to discover the route.", caution: "OKRs cannot repair a bad strategy kernel. Measure What Matters only after deciding what matters." },
    ],
    rapid: ["Objective = what; KR = measurable outcome", "3–5 objectives, 3–5 KRs", "Public, multi-directional alignment", "Focus Align Track Stretch", "CFRs humanize the system", "Never confuse OKRs with strategy or compensation"],
  },
];

export const decoder = [
  { label: "Macro change", clues: "regulation · inflation · demographics · climate · new technology", primary: "PESTEL / External Audit", support: "Megatrends → Five Forces", why: "The cause sits outside one firm. First name the external fact, then show how it changes industry pressure." },
  { label: "Industry profitability", clues: "power · entry barrier · substitute · price war · switching cost", primary: "Porter’s Five Forces", support: "Generic Strategies", why: "The issue is the collective strength of industry forces and the position needed to cope with them." },
  { label: "Growth route", clues: "new product · new country · more share · entirely new business", primary: "Ansoff Matrix", support: "VRIO + NPV", why: "Classify product/market newness, then test whether resources support the move and whether it creates value." },
  { label: "Hidden advantage", clues: "brand · patent · data · culture · ecosystem · know-how", primary: "VRIO / RBV", support: "Ex-ante & Ex-post Limits", why: "The clue is firm-specific and potentially hard to transfer or imitate." },
  { label: "Rapid change", clues: "disruption · adaptation · obsolete capabilities · pivot", primary: "Dynamic Capabilities", support: "Deliberate–Emergent + Upheaval", why: "The firm must sense, seize, and reconfigure—not merely exploit its current strengths." },
  { label: "Vague strategy", clues: "vision slogans · 20% growth · long wish list · no diagnosis", primary: "Rumelt’s Kernel", support: "Trade-offs", why: "Turn ambition into a diagnosis, guiding policy, and coherent actions with explicit choices." },
  { label: "Plan failed / surprise won", clues: "experiment · pivot · learning · unintended pattern", primary: "Deliberate–Emergent Spectrum", support: "Strategy as Craft", why: "Compare intended and realized behavior and explain how learning formed the actual strategy." },
  { label: "Execution gap", clues: "silos · slow decisions · wrong incentives · unclear reporting", primary: "7S / Alignment", support: "Structure Follows Strategy", why: "The strategy may be sound, but organizational elements do not mutually reinforce it." },
  { label: "Operations vs innovation", clues: "reliability conflict · legacy IT · experimental unit · CIO/CDO", primary: "Structural Ambidexterity", support: "Dynamic Capabilities", why: "The firm must exploit today while separately but coherently exploring tomorrow." },
  { label: "Ethical exposure", clues: "privacy · bias · vulnerable users · greenwashing · reputation", primary: "CSR / CDR + Stakeholder Analysis", support: "Value Stick + Ethical Heuristics", why: "Test obligations and harm, then show how responsible action affects stakeholder value and risk." },
  { label: "Investment choice", clues: "cash flows · acquisition · capex · WACC · break-even", primary: "NPV / TVM", support: "BSC + Scenario Analysis", why: "Discount incremental cash flows, disclose assumptions, and supplement financial results with strategic evidence." },
  { label: "Wrong behavior from targets", clues: "gaming · short-termism · tunnel vision · local optimization", primary: "CPM Dysfunctions", support: "Motivation + KPI Redesign", why: "The measurement system is shaping behavior; broaden metrics and redesign incentives/governance." },
  { label: "Strategy not actionable", clues: "too many priorities · invisible progress · misaligned teams", primary: "OKRs", support: "CFRs + CPM", why: "Translate priorities into a small set of transparent outcome measures with frequent learning." },
];

export const scenarios = [
  { title: "The cheap airline trap", prompt: "A mid-market airline adds luxury lounges while still advertising the lowest fares. Its cost base rises, but customers will not pay a premium.", answer: "Porter’s Generic Strategies / stuck in the middle", reasoning: "The firm combines incompatible positions without either a lowest-cost activity system or valued differentiation. Recommend a clear position and trade-offs; use the Value Stick to show whether lounge benefits raise WTP enough to cover cost." },
  { title: "A regulation arrives", prompt: "A new EU rule requires explainability and bias audits for automated credit decisions. Compliance costs rise, but customers increasingly value trustworthy providers.", answer: "PESTEL → Five Forces → SWOT", reasoning: "The rule is Legal/Political external fact. It may raise entry barriers and costs, changing Five Forces. A firm with strong governance can pair that strength with the trust opportunity (SO/ST) and differentiate." },
  { title: "The copied feature", prompt: "A SaaS firm launches a popular feature. Rivals reproduce it within six months, and performance returns to the industry average.", answer: "VRIO", reasoning: "The feature was valuable and perhaps briefly rare, but not costly to imitate: temporary advantage. Look for harder-to-copy complements such as data, ecosystem, relationships, culture, or process." },
  { title: "The successful accident", prompt: "Customers use a collaboration tool for a purpose the founders never planned. Usage and retention are strongest in that segment, so the company rebuilds around it.", answer: "Emergent Strategy + Strategy as Craft", reasoning: "The realized pattern was not intended. Leadership recognizes it, learns through use, and turns emergence into deliberate direction. Dynamic capabilities explain sensing, seizing, and reconfiguration." },
  { title: "Great plan, stalled launch", prompt: "A bank announces a digital-first strategy, but approvals remain centralized, bonuses reward branch sales, and legacy teams block API access.", answer: "McKinsey 7S / Organizational Alignment", reasoning: "Strategy conflicts with Structure, Systems, Skills, Staff, and Style. Diagnose these misfits and realign decision rights, incentives, capabilities, and shared values." },
  { title: "Two speeds of IT", prompt: "The CIO rejects unstable experiments; the new digital team bypasses security to move faster. Both claim to protect the company.", answer: "Structural Ambidexterity", reasoning: "Separate exploitation from exploration but coordinate them through shared platforms, governance, resource allocation, and complementary CIO/CDO roles." },
  { title: "The addictive KPI", prompt: "A social app optimizes time-on-platform. Engagement rises, but teenage well-being concerns, regulatory scrutiny, and employee discomfort intensify.", answer: "Corporate Digital Responsibility + CPM Dysfunction", reasoning: "The metric creates tunnel vision and ethical risk. Apply CSR/CDR, stakeholder and unintended-harm checks, then balance engagement with safety, well-being, incident, and trust measures." },
  { title: "Profit but no cash", prompt: "A fast-growing wholesaler reports rising net income but repeatedly struggles to pay suppliers. Receivables and inventory are expanding quickly.", answer: "Cash Flow + Working Capital Ratios", reasoning: "Profit is not cash. Inspect operating cash flow, DSO, DIO, DPO, and CCC. Growth may be tying cash up faster than it is collected." },
  { title: "Moonshot losses", prompt: "A new division loses billions while building a platform management believes could shape a future market. Directors ask whether to shut it down now.", answer: "NPV + Balanced Scorecard + Real Options", reasoning: "Current profit alone is insufficient. Model scenarios and discounted cash flows, then use customer, process, and learning indicators as evidence of momentum. State uncertainty and stage-gate the investment." },
  { title: "Green dashboard, bad customers", prompt: "Support agents hit their target for short call duration, yet repeat contacts and customer churn increase.", answer: "Performance Measurement Dysfunction", reasoning: "Tunnel vision, gaming, and suboptimization follow a narrow KPI. Add first-contact resolution and satisfaction, align incentives, and use qualitative reviews." },
  { title: "Twenty-seven priorities", prompt: "Every department calls its projects strategic. Teams cannot see dependencies and quarterly reviews become status-report theater.", answer: "OKRs", reasoning: "Use a few public Objectives and outcome KRs, cross-team dependencies, a common cadence, and CFRs. But first use Rumelt’s kernel to ensure leadership has made real choices." },
  { title: "New continent, same product", prompt: "A successful German meal-kit firm takes its current service to Southeast Asia using new local distribution partners.", answer: "Ansoff: Market Development", reasoning: "The product is substantially existing while the geography/customer market is new. Then test local PESTEL, Five Forces, and whether capabilities transfer." },
];

export const formulas = [
  ["Gross margin", "(Revenue − COGS) / Revenue", "Core production profitability"],
  ["EBITDA margin", "EBITDA / Revenue", "Operating profitability before D&A"],
  ["Operating margin", "EBIT / Revenue", "Efficiency before financing and tax"],
  ["Net margin", "Net income / Revenue", "Overall profitability"],
  ["ROA", "Net income / Total assets", "Profit generated by assets"],
  ["ROE", "Net income / Equity", "Shareholder return; check leverage"],
  ["ROCE", "EBIT / (Total assets − Current liabilities)", "Return on long-term capital"],
  ["Current ratio", "Current assets / Current liabilities", "Near-term solvency"],
  ["Quick ratio", "(Current assets − Inventory) / Current liabilities", "Urgent liquidity"],
  ["DSO", "Avg receivables / Credit sales × 365", "Days to collect"],
  ["DIO", "Avg inventory / COGS × 365", "Days inventory held"],
  ["DPO", "Avg payables / COGS × 365", "Days to pay suppliers"],
  ["CCC", "DIO + DSO − DPO", "Days cash is tied up"],
  ["Future value", "PV × (1 + i)ⁿ", "Compound today’s money forward"],
  ["Present value", "FV / (1 + i)ⁿ", "Discount future money to today"],
  ["NPV", "Σ CFₜ / (1 + r)ᵗ", "Accept if positive, subject to assumptions"],
];

export const sources = [
  ["Definition", "https://awe-hnu.de/lectures/SPM/26WT/definition/"],
  ["Competition", "https://awe-hnu.de/lectures/SPM/26WT/competition/"],
  ["Resources", "https://awe-hnu.de/lectures/SPM/26WT/resources/"],
  ["Formation", "https://awe-hnu.de/lectures/SPM/26WT/formation/"],
  ["Organization", "https://awe-hnu.de/lectures/SPM/26WT/organization/"],
  ["Ethics", "https://awe-hnu.de/lectures/SPM/26WT/ethics/"],
  ["CPM", "https://awe-hnu.de/lectures/SPM/26WT/cpm/"],
  ["OKRs", "https://awe-hnu.de/lectures/SPM/26WT/OKRs/"],
  ["Meta Case Preparation", "https://awe-hnu.de/lectures/SPM/26WT/case-2/preparation.html"],
];
