<script setup lang="ts">
const investment=ref(250), rate=ref(9), flows=ref([70,80,95,110])
const npv=computed(()=>-investment.value+flows.value.reduce((s,x,i)=>s+x/Math.pow(1+rate.value/100,i+1),0))
useSeoMeta({title:'Meta Case — SPM Field Guide'})
</script>
<template><main class="lessonPage"><header class="lessonTopbar"><NuxtLink class="brand" to="/"><span>SPM</span> Field Guide</NuxtLink><div class="lessonTopActions"><NuxtLink to="/#map">Topics</NuxtLink><NuxtLink to="/trainer">Trainer</NuxtLink></div></header><section class="lessonHero"><div><span>CASE 2 · INTEGRATION</span><h1>Strategy as a system<em>একটি case-এ models connect করো</em></h1><p>External pressure থেকে resources, strategic choice, organization, ethics, measurement ও OKRs—একটি causal chain বানাও।</p></div><aside><small>MODEL CHAIN</small><p>PESTEL → Five Forces → VRIO → Kernel → 7S → Ethics → CPM → OKRs</p></aside></section>
<section class="lessonIntro"><div class="sectionIntro"><span>HOW TO PREPARE</span><h2>Model dump নয়—handoff explain করো.</h2></div><div class="mechanismGrid"><div><b>1. Diagnose context</b><p>PESTEL ও Five Forces দিয়ে external pressure.</p></div><div><b>2. Test feasibility</b><p>VRIO দিয়ে firm-specific ability.</p></div><div><b>3. Make a choice</b><p>Rumelt Kernel: challenge, policy, coherent actions.</p></div><div><b>4. Execute & learn</b><p>7S, ethics, CPM এবং OKR cadence.</p></div></div></section>
<section class="modelsSection"><div class="sectionIntro"><span>INTERACTIVE NPV CHECK</span><h2>Investment কি value যোগ করে?</h2></div><div class="npvDesk"><div class="npvInputs"><label>Initial investment<input v-model.number="investment" type="number"></label><label>Discount rate %<input v-model.number="rate" type="number"></label><label v-for="(_,i) in flows" :key="i">Year {{i+1}} cash flow<input v-model.number="flows[i]" type="number"></label></div><div class="npvScreen"><small>NPV</small><strong>{{npv>=0?'+':'−'}}€{{Math.abs(npv).toFixed(2)}}</strong><b>{{npv>=0?'VALUE-CREATING SIGNAL':'REASSESS SIGNAL'}}</b><p>Forecast risk ও stakeholder effects আলাদাভাবে discuss করো।</p></div></div></section>
<section class="practiceSection"><div class="sectionIntro"><span>EXAM TEMPLATE</span><h2>Integration answer flow.</h2></div><article class="scenarioCard"><ol><li>Quote the decisive signal.</li><li>Name the lead model and mechanism.</li><li>Map 2–3 case facts.</li><li>Add a model only where a question remains.</li><li>Recommend action, metric, owner and caveat.</li></ol><NuxtLink to="/trainer">Practice mixed scenarios →</NuxtLink></article></section></main></template>
