<script setup lang="ts">
import { topics, decoder, scenarios, formulas } from '~/studyData'
const query=ref(''); const active=ref(0); const scenario=ref(0); const showAnswer=ref(false)
const filtered=computed(()=>topics.filter(t=>(t.title+t.subtitle+t.concepts.map(c=>c.name).join(' ')).toLowerCase().includes(query.value.toLowerCase())))
useSeoMeta({title:'SPM Field Guide — HNU AIDA'})
</script>
<template>
<main>
  <header class="topbar"><NuxtLink class="brand" to="/"><span>SPM</span> Field Guide</NuxtLink><nav><a href="#map">Course map</a><a href="#learn">Learn</a><NuxtLink to="/trainer">Trainer</NuxtLink><NuxtLink class="navCta" to="/case-2">Meta Case →</NuxtLink></nav></header>
  <section class="hero"><div class="heroCopy"><span class="eyebrow">HNU · AIDA · STRATEGY & PERFORMANCE MANAGEMENT</span><h1>Scenario দেখো.<br><em>Signal ধরো.</em><br>Strategy বেছে নাও.</h1><p>বাংলায় গভীর explanation, exam-ready English terminology, interactive models এবং daily recall—একটি personal, offline-friendly study system.</p><div class="heroActions"><a href="#map">Start the course ↓</a><NuxtLink to="/trainer">Practice unseen cases</NuxtLink></div></div><aside class="heroCard"><small>THE EXAM ALGORITHM</small><ol><li><b>Signal</b><span>কোন fact decisive?</span></li><li><b>Model</b><span>কোন framework সেই issue explain করে?</span></li><li><b>Evidence</b><span>Case facts model-এ map করো</span></li><li><b>Action</b><span>Diagnosis থেকে recommendation</span></li><li><b>Caveat</b><span>Limit বা assumption</span></li></ol></aside></section>
  <section id="map" class="courseMap"><div class="sectionIntro"><span>01 / COURSE MAP</span><h2>আটটি topic, একটি connected flow.</h2><p>প্রতিটি topic আগের প্রশ্নের limitation ধরে পরের strategic question-এ যায়।</p></div><div class="searchWrap"><input v-model="query" placeholder="Model বা issue খুঁজো—VRIO, ethics, churn…"></div><div class="topicGrid"><NuxtLink v-for="t in filtered" :key="t.id" :to="`/topics/${t.id}`" class="topicCard"><span>{{t.number}}</span><h3>{{t.title}}</h3><p>{{t.subtitle}}</p><small>{{t.question}}</small><b>Open detailed lesson →</b></NuxtLink></div></section>
  <section id="learn" class="learnSection"><div class="sectionIntro"><span>02 / MODEL DECODER</span><h2>Issue থেকে model খুঁজো.</h2></div><div class="topicTabs"><button v-for="(t,i) in topics" :key="t.id" :class="{active:active===i}" @click="active=i">{{t.number}} {{t.title}}</button></div><article class="conceptPanel"><small>CORE QUESTION</small><h2>{{topics[active].question}}</h2><p>{{topics[active].answer}}</p><div class="conceptGrid"><div v-for="c in topics[active].concepts" :key="c.name"><h3>{{c.name}}</h3><b>{{c.memory}}</b><p>{{c.signal}}</p></div></div><NuxtLink :to="`/topics/${topics[active].id}`">Study full topic →</NuxtLink></article></section>
  <section class="decoderSection"><div class="sectionIntro"><span>03 / SIGNAL LIBRARY</span><h2>এই clue দেখলে কী ভাববে?</h2></div><div class="decoderGrid"><article v-for="d in decoder" :key="d.label"><small>{{d.label}}</small><h3>{{d.clues}}</h3><p><b>{{d.primary}}</b></p><span>{{d.why}}</span></article></div></section>
  <section class="practiceSection"><div class="sectionIntro"><span>04 / QUICK CASE</span><h2>Model name আগে নয়—issue আগে.</h2></div><article class="scenarioCard"><small>{{scenarios[scenario].title}}</small><p>{{scenarios[scenario].prompt}}</p><button @click="showAnswer=!showAnswer">{{showAnswer?'Hide':'Reveal'}} diagnosis</button><div v-if="showAnswer"><h3>{{scenarios[scenario].answer}}</h3><p>{{scenarios[scenario].reasoning}}</p></div><button @click="scenario=(scenario+1)%scenarios.length;showAnswer=false">Next case →</button></article></section>
  <section class="formulaSection"><div class="sectionIntro"><span>05 / FORMULA SHELF</span><h2>Calculate → interpret → qualify.</h2></div><div class="formulaGrid"><article v-for="f in formulas" :key="f[0]"><b>{{f[0]}}</b><code>{{f[1]}}</code><p>{{f[2]}}</p></article></div></section>
  <footer><b>SPM Field Guide</b><p>Personal study material for HNU AIDA · Strategy & Performance Management.</p></footer>
</main>
</template>
