<script setup lang="ts">
import { scenarios } from '~/studyData'
const step=ref(0), reveal=ref(false), selected=ref(''), confidence=ref('')
const fields=reactive<Record<string,string>>({Signal:'',Model:'',Evidence:'',Action:'',Caveat:''})
const options=computed(()=>{const c=scenarios[step.value].answer; const p=['PESTEL','Five Forces','VRIO','Rumelt’s Strategy Kernel','McKinsey 7S','Corporate Digital Responsibility','NPV + Balanced Scorecard','OKRs','Ansoff Matrix','Performance Measurement Dysfunction']; return [c,...p.filter(x=>x!==c)].slice(0,4)})
const current=computed(()=>scenarios[step.value])
function next(){step.value=(step.value+1)%scenarios.length;reveal.value=false;selected.value='';confidence.value=''}
useSeoMeta({title:'Exam Trainer — SPM Field Guide'})
</script>
<template><main class="trainerPage"><header class="lessonTopbar"><NuxtLink class="brand" to="/"><span>SPM</span> Field Guide</NuxtLink><div class="lessonTopActions"><NuxtLink to="/#map">Topics</NuxtLink><NuxtLink to="/case-2">Meta Case</NuxtLink><a class="navCta" href="#answer-studio">Write answer</a></div></header>
<section class="trainerHero"><div><span>EXAM TRANSFER LAB</span><h1>Model মুখস্থ নয়.<br><em>Signal discriminate করো.</em></h1><p>Dominant issue → lead model → evidence → action → caveat.</p></div><div class="trainerRule"><small>THE RULE</small><strong>One lead model</strong><p>Supporting model কেবল নতুন explanatory কাজ করলে যোগ করো।</p></div></section>
<section class="mixedQuiz"><div class="quizHeader"><span>MIXED CASE {{step+1}} / {{scenarios.length}}</span></div><div class="quizBody"><div class="casePrompt"><small>TOPIC HIDDEN</small><h2>{{current.title}}</h2><p>{{current.prompt}}</p><b>Which model should lead?</b></div><div class="modelChoices"><button v-for="o in options" :key="o" :disabled="!!selected" :class="selected?o===current.answer?'correct':o===selected?'wrong':'muted':''" @click="selected=o;reveal=true">{{o}}</button></div></div><div v-if="reveal" class="quizFeedback"><div><span>{{selected===current.answer?'✓ CORRECT':'✕ RECHECK'}}</span><h3>{{current.answer}}</h3><p>{{current.reasoning}}</p></div><div class="confidence"><b>কতটা sure ছিলে?</b><button v-for="x in ['Knew it','Unsure','Guessed']" :key="x" :class="{active:confidence===x}" @click="confidence=x">{{x}}</button></div></div><div class="quizActions"><button @click="next">Next case →</button></div></section>
<section id="answer-studio" class="answerStudio"><div class="studioIntro"><span>BLANK-PAGE TRANSFER</span><h2>SMEAC answer লিখো.</h2><p>লেখা browser-এই থাকে।</p></div><div class="studioGrid"><label v-for="(_,key) in fields" :key="key"><span>{{key}}</span><textarea v-model="fields[key]" :placeholder="key==='Signal'?'Decisive fact':key==='Model'?'Framework + why':key==='Evidence'?'Facts mapped to mechanism':key==='Action'?'Specific recommendation':'Risk or assumption'"></textarea></label></div></section></main></template>
